{{- if .Values.admissionWebhooks.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: multicluster.x-k8s.io.workapi-webhook
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.webhookService.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.webhookService.port }}
      protocol: TCP
      name: https
  {{- end -}}
