replicaCount: 1

image:
  repository: registryUrl/repository
  pullPolicy: Always
  tag: "tag version"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "work-controller-sa"

podAnnotations: {
  prometheus.io/scrape: "true",
  prometheus.io/path: "/metrics",
  prometheus.io/port: "8080"
}

podSecurityContext: {}

securityContext: {
    allowPrivilegeEscalation: false,
    capabilities: {
        drop: [
          ALL
        ]
    },
    privileged : false
}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
