# Default values for WorkAPI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Work-API core parameters

## @param imageRegistry Image registry
imageRegistry: "ghcr.io"
## @param image.repository Image repository
## @param image.tag Image tag
## @param image.pullPolicy Image pull policy
image:
  repository: azure/k8s-work-api
  tag: latest
  pullPolicy: Always


## @param webhookService.type WorkAPI webhook service type
## @param webhookService.port WorkAPI webhook service port
webhookService:
  type: ClusterIP
  port: 9443

admissionWebhooks:
  enabled: true
  failurePolicy: Fail
  certificate:
    mountPath: /etc/k8s-webhook-certs
  patch:
    enabled: true
    image:
      repository: todo
      tag: v2.4.1
      pullPolicy: IfNotPresent
    nodeSelector: {}
    affinity: {}
    tolerations: []
  appConversion:
    enabled: false
  certManager:
    enabled: false
    revisionHistoryLimit: 3