apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: test-work
  namespace: default
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-nginx
        namespace: default
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: test-nginx
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: test-nginx
          spec:
            containers:
            - image: nginx:1.14.2
              name: nginx
              ports:
              - containerPort: 80
              resources: {}
    - apiVersion: v1
      kind: Service
      metadata:
        labels:
          run: test-nginx
        name: test-nginx
        namespace: default
      spec:
        ports:
        - port: 80
          protocol: TCP
          targetPort: 0
        selector:
          run: test-nginx
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: fleet-admin
      rules:
        - apiGroups: ['fleet.azure.com']
          resources: ['*']
          verbs: ['*']
        - nonResourceURLs: ['*']
          verbs: ["get"]