apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: test-work
  namespace: fleet-system
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-nginx
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: test-nginx
        template:
          metadata:
            labels:
              app: test-nginx
          spec:
            containers:
            - image: nginx:1.22.0
              name: nginx
              ports:
              - containerPort: 80
    - apiVersion: v1
      kind: Service
      metadata:
        labels:
          run: test-nginx-2
        name: test-nginx-2
        namespace: default
      spec:
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 80
        selector:
          run: test-nginx
