apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: work-role
rules:
  - apiGroups: ["multicluster.x-k8s.io"]
    resources: ["works", "appliedworks", "appliedworks/status"]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: work-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: {{ include "deploy-work-api.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: work-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: work-role
subjects:
  - kind: ServiceAccount
    name: {{ include "deploy-work-api.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
